In [6]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
import numpy as np
import joblib


music_data = pd.read_csv("music.csv")
music_data
# X = music_data.drop(columns=['genre'])
# y = music_data['genre']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# model = DecisionTreeClassifier()
# model.fit(X_train, y_train)
# predictions = model.predict(X_test)
# score = accuracy_score(y_test, predictions)
# score

age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [5]:
model = DecisionTreeClassifier()
music_data = pd.read_csv("music.csv")
X = music_data.drop(columns=['genre'])
y = music_data['genre']
model.fit(X, y)
tree.export_graphviz(model, out_file='music-recommender.dot', 
                     feature_names=['age', 'gender'], 
                     class_names=sorted(y.unique()), 
                    label='all',
                    rounded=True,
                    filled=True)
# joblib.dump(model, "music-recommender.joblib")

In [3]:
# model = joblib.load('music-recommender.joblib')
# predictions = model.predict([[1, 0]])
# predictions

In [103]:
# music_data

In [13]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension of numpy arrays
a.ndim
b.ndim

2

In [8]:
b.shape

(2, 3)

In [9]:
a.shape

(3,)

In [14]:
# Get Type
a.dtype

dtype('int16')

In [16]:
a.itemsize

2

In [17]:
a.size

3

In [23]:
a.nbytes

6

In [31]:
b[1, :]

array([6., 5., 4.])

In [32]:
b[1,2] = 25
print(b)

[[ 9.  8.  7.]
 [ 6.  5. 25.]]


In [17]:
# Three Dimensional array
c = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
c[1,0, 1]

6

In [10]:
d = np.ones((2,3, 4,3))
# print(d)

In [11]:
e = np.random.rand(4,2)
print(e)

[[0.53846846 0.87894759]
 [0.3074102  0.07906798]
 [0.5365561  0.3872805 ]
 [0.24929314 0.23431084]]


In [14]:
def binary_search_tree(arr, search_term):
    start_count, arr_count = 0, len(arr) - 1
    if(len(arr) <= 0):
        print("No Item in the array")
        return -1
    while start_count <= arr_count:
        mid = (arr_count + start_count) // 2
        mid_num_val = arr[mid]
        if mid_num_val == arr[mid]:
            print("this is the value ", mid)
            return mid
        elif mid_num_val >= search_term:
            arr_count = mid - 1;
        elif mid_num_val <= search_term:
            start_count = mid + 1
    return -1
            
result = binary_search_tree([8,4,2,4,5,6,7,], 5)
result

this is the value  3


3